### ISSUE TITLE
自定义NexT.Gemini主题的样式 | ExtremeGTR's Blog

### ISSUE THREAD

**Issue by ExtremeGTR** [ExtremeGTR/extremegtr.github.io#3]
https://extremegtr.github.io/2017/09/27/Customize-NexT-Gemini-theme/

**Comment by ghost** [comment]
你好，请问你一个问题：为什么我改了之后在首页上"阅读全文" 显示不全？然后我看你的首页阅读全文也是显示不全。纯小白完全不知道怎么修改，麻烦博主告知！！！

**Comment by ExtremeGTR** [comment]
@RandomFool
我看了下，问题出在这个配置：
```css
// 文章内的超链接
.post-body a {
    color: #0593d3;
    border-bottom: none; // 这行配置会把 <<阅读全文>> 这个按钮的底部去掉。
    &:hover {
        color: #FF4500;
    }
}
```
其实不配这个也行。改这些前端的东西对于我来说还是挺麻烦的，我对页面这些样式也是一知半解，这个自定义我也是花了很大功夫才搞成这样。
如果想自定义超链接的样式又想这个按钮的底部保留下来，估计我也要琢磨一阵子了。我不是前端大神，对这方面脑子不太好使啊，
有空再搞了，我也不纠结那么多了，你把那一行配置去掉，那按钮就会显示完整了，这是最直接的做法。

**Comment by ghost** [comment]
非常感谢博主！！！

**Comment by Q1ngH3** [comment]
请问博主我想把我的侧栏弄得宽一点应该怎么办 就和你一样宽就行了 我试了网上说的好多方法都不行

**Comment by ExtremeGTR** [comment]
> @xiaoxiaorenwu
> 请问博主我想把我的侧栏弄得宽一点应该怎么办 就和你一样宽就行了 我试了网上说的好多方法都不行 

```
# Manual define the sidebar width
# !!Only available for Gemini Scheme currently
# Leave it empty for the default 240
sidebar_width: 350
```
这个主题配置里自带了啊。。。设置一下就行了。如果是以前v5或者v6的旧版，根据注释所说好像就是只有`Gemini`才能支持这样的改动。。

现在最新版是这样的：
```
sidebar:
  # Sidebar Position.
  position: left
  #position: right

  # Manual define the sidebar width. If commented, will be default for:
  # Muse | Mist: 320
  # Pisces | Gemini: 240
  #width: 300
  width: 350
```
